### GET all users
GET https://cse341-1h7b.onrender.com/users
Content-Type: application/json

### GET user from id
GET https://cse341-1h7b.onrender.com/users/6546a227671d651aa3c3b91b
Content-Type: application/json

### POST Add user
POST https://cse341-1h7b.onrender.com/users HTTP/1.1
Content-Type: application/json

{
	"firstName": "Morgan",
	"lastName": "Burbank",
	"email": "morgan@gmail.com",
	"favoriteColor": "blue",
	"birthday": "09/01/1998"
}

### PUT (Update) user using id
PUT https://cse341-1h7b.onrender.com/users/6546a227671d651aa3c3b91b HTTP/1.1
Content-Type: application/json

{
	"firstName": "Marcello",
	"lastName": "Silverio",
	"email": "brspmso@gmail.com",
	"favoriteColor": "blue",
	"birthday": "07/08/1968"
}

### PATCH (Update) user using id
PATCH https://cse341-1h7b.onrender.com/users/6546a227671d651aa3c3b91b HTTP/1.1
Content-Type: application/json

{
	"firstName": "Luciana",
	"lastName": "Rubeiro Leal Silverio",
	"email": "luciana_silverio@hotmail.com",
	"favoriteColor": "green",
	"birthday": "04/16/1973"
}

### DELETE user from id
DELETE https://cse341-1h7b.onrender.com/users/6546a227671d651aa3c3b91b HTTP/1.1
Content-Type: application/json