### GET all 
GET https://cse341project2-dnhz.onrender.com/recipes
Content-Type: application/json

### GET recipe from id
GET https://cse341project2-dnhz.onrender.com/recipes
Content-Type: application/json

### Add recipe
POST https://cse341project2-dnhz.onrender.com/recipes HTTP/1.1
Content-Type: application/json

{
    "name": "Egg in Toast",
    "ingredients": [
		"Bread",
		"Egg",
		"Butter/Oil",
		"Salt and Pepper"
    ],
    "ingredientQuantity": [
		"1",
		"1",
		"1 tsp",
		""
    ],
    "cookTime": "5min",
    "prepTime": "0",
    "averagePrice": "$",
    "steps": [
		"Cut a hole in the bread",
		"Heat the pan on medium heat then add butter/oil in pan",
		"Toast bread in pan and crack egg in hole",
		"Once egg is firm and bread toasted, flip bread and egg",
		"Add salt and pepper to taste"
    ]
}

### PUT (Update) recipe using id
PUT https://cse341project2-dnhz.onrender.com/recipes HTTP/1.1
Content-Type: application/json

{
    "name": "Egg in Toast",
    "ingredients": [
		"Bread",
		"Egg",
		"Butter/Oil",
		"Salt and Pepper"
    ],
    "ingredientQuantity": [
		"1",
		"1",
		"1 tsp",
		""
    ],
    "cookTime": "5min",
    "prepTime": "0",
    "averagePrice": "$",
    "steps": [
		"Cut a hole in the bread",
		"Heat the pan on medium heat then add butter/oil in pan",
		"Toast bread in pan and crack egg in hole",
		"Once egg is firm and bread toasted, flip bread and egg",
		"Add salt and pepper to taste"
    ]
}

### PATCH (Update) recipe using id
PATCH https://cse341project2-dnhz.onrender.com/recipes HTTP/1.1
Content-Type: application/json

{
    "name": "Egg in Toast",
    "ingredients": [
		"Bread",
		"Egg",
		"Butter/Oil",
		"Salt and Pepper"
    ],
    "ingredientQuantity": [
		"1",
		"1",
		"1 tsp",
		""
    ],
    "cookTime": "5min",
    "prepTime": "0",
    "averagePrice": "$",
    "steps": [
		"Cut a hole in the bread",
		"Heat the pan on medium heat then add butter/oil in pan",
		"Toast bread in pan and crack egg in hole",
		"Once egg is firm and bread toasted, flip bread and egg",
		"Add salt and pepper to taste"
    ]
}

### DELETE recipe from id
DELETE https://cse341project2-dnhz.onrender.com/recipes HTTP/1.1
Content-Type: application/json